Add payload size metrics
TrueCloudLab/frostfs-node pull request #29
Opened 2023-01-25 14:06 UTC by carpawell

Contains commit from https://github.com/nspcc-dev/neofs-node/pull/2125, closes (but not in that repo) https://github.com/nspcc-dev/neofs-node/issues/1794.

2023-01-25 14:46 UTC, fyrchik approved these changes

2023-01-26 06:41 UTC, acid-ant submitted a review, later dismissed

2023-01-26 12:11 UTC, alexvanin approved these changes

2023-01-26 13:33 UTC, fyrchik requested changes

2023-01-26 13:33 UTC, fyrchik commented on CHANGELOG.md
> +- New `neofs_node_object_container_size` metric for tracking size of reqular objects in a container (#2116)
`frostfs_node`

2023-01-26 17:06 UTC, fyrchik approved these changes

2023-01-26 17:06 UTC, merged